# Generated by Django 4.0.3 on 2022-03-30 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='summary',
            new_name='preview',
        ),
    ]
